CC = g++
CFLAGS = -c -g -Wall
LAYER_SRCS = linklayer.cpp
STUB_SRCS = RF.cpp cppStubs.cpp
JAVA_HOME = /usr/lib/jvm/default-java
JVM_INCLUDE = -I$(JAVA_HOME)/include
JVM_LIBRARY = -L$(JAVA_HOME)/jre/lib/amd64/server
LINKFLAGS = -ljvm -shared -fPIC

all: $(LAYER_SRCS) $(STUB_SRCS) WiFiClient.class rf/RF.class
	$(CC) $(LAYER_SRCS) $(STUB_SRCS) -o libnativelib.so $(JVM_INCLUDE) $(JVM_LIBRARY) $(LINKFLAGS)
	

WiFiClient.class: WiFiClient.java
	javac WiFiClient.java 
	
rf/RF.class:
	wget http://www.cs.ups.edu/~brichards/Classes/325/Asmts/Project/Code/C++/rf/RF.class

clean:
	rm -f *.o *.so *.lib *.jnilib WiFiClient*.class
