/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class WiFiClient */

#ifndef _Included_WiFiClient
#define _Included_WiFiClient
#ifdef __cplusplus
extern "C" {
#endif
#undef WiFiClient_CLEAR
#define WiFiClient_CLEAR 0L
#undef WiFiClient_PAUSE
#define WiFiClient_PAUSE 1L
#undef WiFiClient_SAVE
#define WiFiClient_SAVE 2L
/*
 * Class:     WiFiClient
 * Method:    getDefaultAddrs
 * Signature: ()[S
 */
JNIEXPORT jshortArray JNICALL Java_WiFiClient_getDefaultAddrs
  (JNIEnv *, jobject);

/*
 * Class:     WiFiClient
 * Method:    initializeLinkLayer
 * Signature: (S)I
 */
JNIEXPORT jint JNICALL Java_WiFiClient_initializeLinkLayer
  (JNIEnv *, jobject, jshort);

/*
 * Class:     WiFiClient
 * Method:    watchForIncomingData
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_WiFiClient_watchForIncomingData
  (JNIEnv *, jobject);

/*
 * Class:     WiFiClient
 * Method:    sendOutgoingData
 * Signature: (S[B)I
 */
JNIEXPORT jint JNICALL Java_WiFiClient_sendOutgoingData
  (JNIEnv *, jobject, jshort, jbyteArray);

/*
 * Class:     WiFiClient
 * Method:    pollForStreamOutput
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_WiFiClient_pollForStreamOutput
  (JNIEnv *, jobject);

/*
 * Class:     WiFiClient
 * Method:    sendCommand
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_WiFiClient_sendCommand
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
